name: learning_master_background
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-80.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_bladed_axe:
    path: ../double_bladed_axe
  fluro:
    path: ../fluro
  dio: ^4.0.6
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  
  assets:
    - Svg/ç¡¬ç›˜.svg
    - Svg/github.svg
    - Svg/æœç´¢.svg
    - Svg/tag.svg
    - Svg/cog-fill.svg
    - Svg/caret-right.svg
    - Svg/caret-left.svg
    - Svg/delete-fill.svg
    - Svg/edit.svg
    - Svg/plus-circle-fill.svg
    - Svg/nail.svg
  

  
  fonts:
    - family: MiSans
      fonts:
        - asset: fonts/MiSans-Bold.ttf
        - asset: fonts/MiSans-Demibold.ttf
        - asset: fonts/MiSans-ExtraLight.ttf
        - asset: fonts/MiSans-Heavy.ttf
        - asset: fonts/MiSans-Light.ttf
        - asset: fonts/MiSans-Medium.ttf
        - asset: fonts/MiSans-Normal.ttf
        - asset: fonts/MiSans-Regular.ttf
        - asset: fonts/MiSans-Semibold.ttf
        - asset: fonts/MiSans-Thin.ttf
  

